### ISSUE TITLE
Your own pic isn't loading

### ISSUE THREAD

**Issue by inshaal** [gauthamzz/gauthamzz.github.io#1]
Idk if you know about this or not but the place where you hosted your profile pic for your website is returning a 404 Not Found error. 

Link was - http://i.imgsafe.org/5e58f20525.jpg

Also, I checked your resume.. There's space between 'T' and 'opper'

Ignore if you know about these things 😉

**Comment by gauthamzz** [comment]
images were stored in image safe , but there server went down and i lost all data :cry:

**Comment by inshaal** [comment]
Damn :(
